### ISSUE TITLE
Asset Tracker

### ISSUE THREAD

**Issue by Daomephsta** [Polar-Team/Polar#1]
This issue is for keeping track of which assets have been created, and which assets are still pending.
It's not an open request for assets, but a way of keeping track of asset statuses for the Polar team.

**Textures:**
Handled by @Notawallplan
 - [ ] Vermillis Irradiated Redstone. Should look like redstone but more magical. Possibly animated?
 - [ ] Azuras Irradiated Lapis Lazuli. Should look like lapis but more magical. Possibly animated?
 - [ ] Research Journal Texture. Possibly for a special model. At least an unaligned texture, possibly with aligned variants.

**Models:**
Handled by @Daomephsta or @Notawallplan
- [ ] Possible model for the research journal. There would only be a single model even if there were multiple texture variants.

**Comment by Daomephsta** [comment]
Projects are actually a better way of tracking this
